# Generated by Django 3.2 on 2022-05-06 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_knowledge_base', '0003_doc_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='部门', max_length=50, verbose_name='部门')),
                ('pinyin', models.CharField(help_text='部门拼音字母', max_length=100, verbose_name='部门拼音字母')),
                ('short_pinyin', models.CharField(help_text='部门拼音字母简写', max_length=30, verbose_name='部门拼音字母简写')),
                ('level', models.SmallIntegerField(blank=True, choices=[(1, '一级部门'), (2, '二级部门'), (3, '三级部门'), (4, '四级部门'), (126, '供应商'), (127, '其它'), (0, '总部')], help_text='部门级别', null=True, verbose_name='部门级别')),
                ('introduction', models.CharField(blank=True, help_text='部门简介', max_length=500, null=True, verbose_name='部门简介')),
                ('info', models.CharField(default='', help_text='部门信息', max_length=100, verbose_name='部门信息')),
                ('create_time', models.DateField(help_text='创建时间', verbose_name='创建时间')),
                ('superior_department', models.ForeignKey(blank=True, help_text='上级部门', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub', to='app_cmdb.department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='Logon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='登录名称', max_length=50, verbose_name='登录名称')),
                ('username', models.CharField(help_text='用户名', max_length=20, verbose_name='用户名')),
                ('password', models.CharField(help_text='密码', max_length=50, verbose_name='密码')),
                ('encryption_type', models.CharField(blank=True, help_text='加密方式', max_length=10, null=True, verbose_name='加密方式')),
                ('create_time', models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '登录',
                'verbose_name_plural': '登录',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='供应商', max_length=50, verbose_name='供应商')),
                ('pinyin', models.CharField(help_text='供应商拼音字母', max_length=100, verbose_name='供应商拼音字母')),
                ('short_pinyin', models.CharField(help_text='供应商拼音字母简写', max_length=30, verbose_name='供应商拼音字母简写')),
                ('rating', models.IntegerField(default=75, help_text='供应商评级', verbose_name='供应商评级')),
                ('introduction', models.CharField(blank=True, help_text='供应商简介', max_length=300, null=True, verbose_name='供应商简介')),
                ('contact', models.CharField(help_text='供应商联系人', max_length=50, verbose_name='供应商联系人')),
                ('phone', models.CharField(help_text='供应商联系电话', max_length=30, verbose_name='供应商联系电话')),
                ('email', models.EmailField(help_text='供应商 Email', max_length=254, verbose_name='供应商 Email')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='系统名称', max_length=50, verbose_name='系统名称')),
                ('short_name', models.CharField(help_text='系统简称', max_length=30, verbose_name='系统简称')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '在线'), (2, '下线'), (3, '待上线'), (4, '其它')], default=1, help_text='系统在线状态', verbose_name='系统在线状态')),
                ('env', models.PositiveSmallIntegerField(choices=[(1, '生产环境'), (2, '生产环境'), (3, '灾备环境'), (4, '生产测试环境'), (99, '其它')], default=1, help_text='系统环境', verbose_name='系统环境')),
                ('address', models.CharField(help_text='系统访问地址', max_length=150, verbose_name='系统访问地址')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='系统更新时间', verbose_name='系统更新时间')),
                ('create_time', models.DateField(auto_now_add=True, help_text='系统上线时间', verbose_name='系统上线时间')),
                ('department', models.ManyToManyField(blank=True, help_text='关联部门', null=True, to='app_cmdb.Department', verbose_name='关联部门')),
                ('manager', models.ManyToManyField(help_text='关联系统负责人', to=settings.AUTH_USER_MODEL, verbose_name='关联系统负责人')),
                ('supplier', models.ForeignKey(blank=True, help_text='供应商', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cmdb.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '系统',
                'verbose_name_plural': '系统',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='品牌', max_length=30, verbose_name='品牌')),
                ('version', models.CharField(blank=True, help_text='型号', max_length=50, null=True, verbose_name='型号')),
                ('name', models.CharField(help_text='设备名', max_length=100, verbose_name='设备名')),
                ('core', models.IntegerField(blank=True, help_text='cpu 核心数', null=True, verbose_name='cpu 核心数')),
                ('memory', models.CharField(blank=True, help_text='内存', max_length=64, null=True, verbose_name='内存')),
                ('disk', models.CharField(blank=True, help_text='硬盘', max_length=64, null=True, verbose_name='硬盘')),
                ('ost', models.CharField(choices=[('Linux', 'Linux'), ('Unix', 'Unix'), ('MacOS', 'MacOS'), ('BSD', 'BSD'), ('Windows', 'Windows'), ('Other', 'Other')], default='Windows', help_text='操作系统类型', max_length=20, verbose_name='操作系统类型')),
                ('osv', models.CharField(blank=True, help_text='操作系统版本', max_length=50, null=True, verbose_name='操作系统版本')),
                ('virtual', models.BooleanField(default=False, help_text='是否虚拟机', verbose_name='是否虚拟机')),
                ('create_time', models.DateField(auto_now_add=True, help_text='添加时间', verbose_name='添加时间')),
                ('ip', models.CharField(help_text='ip地址', max_length=128, verbose_name='ip地址')),
                ('logon', models.ManyToManyField(blank=True, help_text='登陆信息', null=True, to='app_cmdb.Logon', verbose_name='登陆信息')),
                ('parent', models.ForeignKey(blank=True, help_text='宿主机', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child', to='app_cmdb.machine', verbose_name='宿主机')),
            ],
            options={
                'verbose_name': '机器',
                'verbose_name_plural': '机器',
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='License 名称', max_length=50, verbose_name='License 名称')),
                ('expire', models.DateField(help_text='产品授权', verbose_name='授权过期时间')),
                ('license', models.CharField(default='', help_text='license 内容', max_length=200, verbose_name='license 内容')),
                ('license_file', models.FileField(blank=True, help_text='license 文件', null=True, upload_to='uploads/license/%Y/%m/%d/', verbose_name='license 文件')),
                ('version', models.CharField(default='', help_text='版本', max_length=30, verbose_name='版本')),
                ('num', models.IntegerField(default=1, help_text='授权数量', verbose_name='授权数量')),
                ('remark', models.CharField(blank=True, help_text='license 补充信息', max_length=200, null=True, verbose_name='license 补充信息')),
                ('create_time', models.DateField(auto_now=True, help_text='授权/更新日期', verbose_name='授权/更新日期')),
                ('supplier', models.ForeignKey(blank=True, help_text='授权机构', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cmdb.supplier', verbose_name='授权机构')),
            ],
            options={
                'verbose_name': 'License',
                'verbose_name_plural': 'License',
            },
        ),
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='总部机房', max_length=70, verbose_name='机房名称')),
                ('address', models.CharField(default='总部机房', max_length=150, verbose_name='机房地址')),
                ('create_time', models.DateField(help_text='机房建成时间', verbose_name='机房建成时间')),
                ('remark', models.CharField(help_text='备注', max_length=150, verbose_name='备注')),
                ('responsible', models.ForeignKey(blank=True, help_text='负责人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '机房',
                'verbose_name_plural': '机房',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='姓名', max_length=100, verbose_name='姓名')),
                ('pinyin', models.CharField(help_text='姓名拼音字母', max_length=200, verbose_name='姓名拼音字母')),
                ('short_pinyin', models.CharField(help_text='姓名拼音字母简写', max_length=30, verbose_name='姓名拼音字母简写')),
                ('phone', models.CharField(blank=True, help_text='电话', max_length=20, null=True, verbose_name='电话')),
                ('email', models.EmailField(help_text='电子邮箱', max_length=254, verbose_name='电子邮箱')),
                ('introduction', models.CharField(blank=True, help_text='个人简介', max_length=300, null=True, verbose_name='个人简介')),
                ('department', models.ForeignKey(blank=True, help_text='所属部门', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cmdb.department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='机柜名称', max_length=50, verbose_name='机柜名称')),
                ('address', models.CharField(help_text='位置', max_length=150, verbose_name='位置')),
                ('rack_num', models.SmallIntegerField(help_text='机架数量', verbose_name='机架数量')),
                ('create_time', models.DateField(help_text='启用时间', verbose_name='启用时间')),
                ('idc', models.ForeignKey(blank=True, help_text='所属机房', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_cmdb.idc', verbose_name='所属机房')),
            ],
            options={
                'verbose_name': '机柜',
                'verbose_name_plural': '机柜',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='应用名称', max_length=50, verbose_name='应用名称')),
                ('env', models.PositiveSmallIntegerField(choices=[(1, '生产环境'), (2, '测试环境'), (3, '灾备环境'), (4, '生产测试环境'), (99, '其它')], default=1, help_text='系统环境', verbose_name='系统环境')),
                ('port', models.CharField(blank=True, help_text='端口号', max_length=6, null=True, verbose_name='端口号')),
                ('location', models.CharField(help_text='安装位置', max_length=150, verbose_name='安装位置')),
                ('conf', models.CharField(default='./conf', help_text='配置文件路径', max_length=100, verbose_name='配置文件路径')),
                ('log', models.CharField(default='./logs', help_text='日志文件路径', max_length=100, verbose_name='日志文件路径')),
                ('execution', models.CharField(default='./bin', help_text='程序文件路径', max_length=100, verbose_name='程序文件路径')),
                ('app_type', models.PositiveSmallIntegerField(choices=[(1, '应用'), (2, 'web 服务器'), (3, '数据库'), (99, '其它')], default=1, verbose_name='应用类型')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('create_time', models.DateField(auto_now_add=True, help_text='创建日期', verbose_name='创建日期')),
                ('license', models.OneToOneField(blank=True, help_text='License', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cmdb.license', verbose_name='License')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cmdb.system', verbose_name='所属系统')),
            ],
            options={
                'verbose_name': '应用',
                'verbose_name_plural': '应用',
            },
        ),
        migrations.CreateModel(
            name='APICenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='接口名称', max_length=100, verbose_name='接口名称')),
                ('pressure', models.BigIntegerField(help_text='压力数据', verbose_name='压力数据')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='接口更新时间', verbose_name='接口更新时间')),
                ('doc', models.ForeignKey(blank=True, help_text='接口文档', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_knowledge_base.doc', verbose_name='接口文档')),
                ('system', models.ForeignKey(help_text='关联系统', on_delete=django.db.models.deletion.CASCADE, to='app_cmdb.system', verbose_name='关联系统')),
            ],
            options={
                'verbose_name': 'API',
                'verbose_name_plural': 'API',
            },
        ),
    ]
