# Generated by Django 3.2 on 2022-05-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='logon',
            field=models.ManyToManyField(help_text='登陆信息', to='app_cmdb.Logon', verbose_name='登陆信息'),
        ),
        migrations.AlterField(
            model_name='system',
            name='department',
            field=models.ManyToManyField(help_text='关联部门', to='app_cmdb.Department', verbose_name='关联部门'),
        ),
    ]
